version: 0.2
phases:
  install:
    commands:
      - echo "Install phase"
        # boto3
      - pip install boto3
        # terraform
      - wget https://releases.hashicorp.com/terraform/1.0.2/terraform_1.0.2_linux_amd64.zip
      - unzip -o terraform_1.0.2_linux_amd64.zip -d /bin
      - rm terraform_1.0.2_linux_amd64.zip
  build:
    commands:
      - echo "Build phase"
       # keep a pointer to project root
      - export PROJECT_ROOT=$(pwd)
      - cd $TF_PATH
      - | 
        if [ -z "$TF_DEPLOY_ROLE" ]; then
          temp_role=$(aws sts assume-role \
            --role-arn $TF_DEPLOY_ROLE \
            --role-session-name "codebuild-tf-deploy")
          export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
          export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
          export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
        fi
      - |
        if [ -z "$TF_VARIABLE_PATH" ]; then
          terraform destroy -auto-approve tf.plan
        else
          terraform destroy -auto-approve -var-file $PROJECT_ROOT/$TF_VARIABLE_PATH tf.plan
        fi
      - | 
        if [ -z "$TF_DEPLOY_ROLE" ]; then
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN
        fi 
  post_build:
    commands:
      - echo "Post Build phase"