version: 0.2
env:
  exported-variables: 
    - "TEST_ERRORS" 
phases:
  install:
    commands:
      - echo "Install phase"
      # - wget https://github.com/accurics/terrascan/releases/download/v1.13.0/terrascan_1.14.0_Linux_x86_64.tar.gz
      # - tar -xf terrascan_1.13.0_Linux_x86_64.tar.gz terrascan && rm terrascan_1.13.0_Linux_x86_64.tar.gz
      - wget https://github.com/accurics/terrascan/releases/download/v1.14.0/terrascan_1.14.0_Linux_x86_64.tar.gz
      - tar -xf terrascan_1.14.0_Linux_x86_64.tar.gz terrascan && rm terrascan_1.14.0_Linux_x86_64.tar.gz
      - install terrascan /usr/local/bin && rm terrascan
  build:
    commands:
      - echo "Build phase"
       # keep a pointer to project root
      - export PROJECT_ROOT=$(pwd)
        # report setup
      - mkdir $PROJECT_ROOT/reports
      - terrascan init
      - terrascan scan -o junit-xml -d $TF_PATH > $PROJECT_ROOT/reports/terrascan.xml; TEST_STATUS=$?
      - terrascan scan -o json -d $TF_PATH > $PROJECT_ROOT/reports/terrascan.json; TEST_STATUS=$?
        # set codepipeine errors
      - export TEST_ERRORS=`less $PROJECT_ROOT/reports/terrascan.json | jq '.results.scan_summary.violated_policies'`
        # display test results
      - echo "terrascan, $TEST_STATUS"
      - cat $PROJECT_ROOT/reports/terrascan.xml
      - less $PROJECT_ROOT/reports/terrascan.json | jq '.results.scan_summary'
      # - cat $PROJECT_ROOT/reports/terrascan.json
  post_build:
    commands:
      - echo "Post Build phase"
# reports: 
#   terrascan:
#     files:
#       - "reports/terrascan.xml"